spring:
    # Thymeleaf 설정
    thymeleaf:
        # Thymeleaf 참조 경로
        prefix: classpath:templates/
        suffix: .html
        # templates 디렉토리에 파일이 있는지 체크
        # -> 없으면 에러 발생
        check-template: true
        # Thymeleaf에 대한 캐시 남김 설정
        # -> 운영시엔 true
        # cache: true
        cache: false

    devtools:
        livereload:
            # 정적 리소스에 변화가 있을 때 즉시 반영 여부
            enabled: true